FEEDBACK_REASON_ROUTE_SUCCESS = "route_success"
FEEDBACK_REASON_MISSING_PARAMS = "missing_params"
FEEDBACK_REASON_TARGET_REQUIRED = "target_required"
FEEDBACK_REASON_SELF_ONLY_BLOCKED = "self_only_blocked"
FEEDBACK_REASON_REROUTE_FAILED = "reroute_failed"
FEEDBACK_REASON_FUZZY_CLARIFY = "fuzzy_target_clarify"
FEEDBACK_REASON_DIRECT_TARGET_REQUIRED = "direct_target_required"

ROUTE_FEEDBACK_REASON_KEYS = frozenset(
    {
        FEEDBACK_REASON_ROUTE_SUCCESS,
        FEEDBACK_REASON_MISSING_PARAMS,
        FEEDBACK_REASON_TARGET_REQUIRED,
        FEEDBACK_REASON_SELF_ONLY_BLOCKED,
        FEEDBACK_REASON_REROUTE_FAILED,
        FEEDBACK_REASON_FUZZY_CLARIFY,
        FEEDBACK_REASON_DIRECT_TARGET_REQUIRED,
    }
)

__all__ = [
    "FEEDBACK_REASON_DIRECT_TARGET_REQUIRED",
    "FEEDBACK_REASON_FUZZY_CLARIFY",
    "FEEDBACK_REASON_MISSING_PARAMS",
    "FEEDBACK_REASON_REROUTE_FAILED",
    "FEEDBACK_REASON_ROUTE_SUCCESS",
    "FEEDBACK_REASON_SELF_ONLY_BLOCKED",
    "FEEDBACK_REASON_TARGET_REQUIRED",
    "ROUTE_FEEDBACK_REASON_KEYS",
]
